[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./deployments" }]
# Optimizer settings for accurate gas measurements
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing configuration
verbosity = 2
gas_reports = ["*"]
gas_snapshots = true

# RPC endpoints
[rpc_endpoints]
fluent-testnet = "https://rpc.testnet.fluent.xyz"
fluent-devnet = "https://rpc.devnet.fluent.xyz"

# Network-specific profiles
[profile.testnet]
rpc_url = "https://rpc.testnet.fluent.xyz"
deployment_file = "./deployments/testnet.json"

[profile.devnet]
rpc_url = "https://rpc.devnet.fluent.xyz"
deployment_file = "./deployments/devnet.json"
