[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Optimizer settings for accurate gas measurements
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing configuration
verbosity = 2
gas_reports = ["*"]
gas_snapshots = true

# Blended execution specific settings
[profile.blended]
src = "src"
rust_src = "math-toolkit/src"
out = "out"
libs = ["lib"]

# Use gblend instead of forge for blended contracts
[build]
via_ir = true
optimizer = true

[rpc_endpoints]
local = "http://127.0.0.1:8545"
fluent_testnet = "https://rpc.dev.fluentlabs.xyz"

[etherscan]
fluent_testnet = { key = "${FLUENT_API_KEY}", url = "https://blockscout.dev.fluentlabs.xyz/api" }

# Gas benchmarking settings
[gas_benchmark]
enabled = true
compare_threshold = 1000  # Gas difference threshold for reporting
output_file = "gas_comparison.json"